# yamllint disable rule:line-length
---
name: confirm oci registry

description: use registry credentials to perform login

inputs:

  registry:
    description: oci compatible registry
    required: false
    default: docker.io

  registry-username:
    description: oci compatible registry
    required: false

  registry-password:
    description: oci compatible registry
    required: false

runs:
  using: "composite"

  steps:
    - name: login to image registry
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        REGISTRY_LOGIN: ${{ inputs.registry-username }}
        REGISTRY_PASSWORD: ${{ inputs.registry-password }}
      run: |
        echo 'write to .docker/config.json is secure in ephemeral runtime environment'
        echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_LOGIN" --password-stdin "$REGISTRY"
