# yamllint disable rule:line-length
---
name: confirm oci registry

description: use $DOCKER_LOGIN and $DOCKER_PASSWORD to perform docker login

inputs:

  registry:
    description: oci compatible registry
    required: false
    default: docker.io

runs:
  using: "composite"

  steps:
    - name: login to image registry
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
      run: |
        echo 'write to .docker/config.json is secure in ephemeral runtime environment'
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin "$REGISTRY"
