# yamllint disable rule:line-length
---
name: install

description: |
  Install gha-tools packages.

  These could be already installed on a pre-configured runner used by the
  shared workflow. Or you may need to install them on the runner,
  or just need a particular version.

  Supported packages:
  - 1Password
  - vault
  - teller
  - Docker Scout
  - snyk
  - bats

inputs:

  op-version:
    description: 1password-cli version
    required: false
    default: ""

  teller-version:
    description: Install Teller version
    required: false
    default: ""

  vault-version:
    description: Install Vault version
    required: false
    default: ""

  scout-version:
    description: Install Hadolint version
    required: false
    default: ""

  snyk-version:
    description: Install Hadolint version
    required: false
    default: ""

  bats-version:
    description: Install Bats version
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: list packages to be installed
      shell: bash
      run: |
        echo "1Password CLI: ${{ inputs.op-version }}"
        echo "Vault: ${{ inputs.vault-version }}"
        echo "Teller: ${{ inputs.teller-version }}"
        echo "Docker Scout: ${{ inputs.scout-version }}"
        echo "Snyk: ${{ inputs.snyk-version }}"

    - name: Install 1Password CLI
      if: ${{ inputs.op-version != '' }}
      uses: 1password/install-cli-action@v2
      with:
        version: ${{ inputs.op-version }}

    - name: Install Vault
      if: ${{ inputs.vault-version != '' }}
      uses: eLco/setup-vault@v1
      with:
        vault_version: ${{ inputs.vault-version }}

      # shell: bash
      # run: |
      #   curl -SLO "https://releases.hashicorp.com/vault/${{ inputs.vault-version }}/vault_${{ inputs.vault-version }}_linux_amd64.zip" > "vault_${{ inputs.vault-version }}_linux_amd64.zip"
      #   sudo unzip "vault_${{ inputs.vault-version }}_linux_amd64.zip" -d /usr/local/bin
      #   sudo rm "vault_${{ inputs.vault-version }}_linux_amd64.zip"

    - name: Install Teller
      if: ${{ inputs.teller-version != '' }}
      uses: spectralops/setup-teller-action@v2
      with:
        teller_version: 1.5.6

      # shell: bash
      # run: |
      #   curl -L https://github.com/tellerops/teller/releases/download/v${{ inputs.teller-version }}/teller_${{ inputs.teller-version }}_Linux_x86_64.tar.gz --output teller_${{ inputs.teller-version }}_Linux_x86_64.tar.gz
      #   tar -xzf teller_${{ inputs.teller-version }}_Linux_x86_64.tar.gz
      #   sudo mv teller /usr/local/bin/teller
      #   rm teller_${{ inputs.teller-version }}_Linux_x86_64.tar.gz

    - name: Install scout
      if: ${{ inputs.scout-version != '' }}
      shell: bash
      env:
        SCOUT_VERSION: ${{ inputs.scout-version }}
      run: |
        #!/bin/bash
        set -euo pipefail

        if [[ "$SCOUT_VERSION" = "latest" ]]; then
          download_version=$(curl -s "https://api.github.com/repos/docker/scout-cli/releases/latest" | jq -r .tag_name)
        else
          download_version="$SCOUT_VERSION"
        fi

        download_url="https://github.com/docker/scout-cli/releases/download/${download_version}/docker-scout_${download_version:1}_linux_amd64.tar.gz"
        curl -fL -O "${download_url}"
        tar -xzf "docker-scout_${download_version:1}_linux_amd64.tar.gz" docker-scout && rm "docker-scout_${download_version:1}_linux_amd64.tar.gz"
        mkdir -p "$HOME/.docker/cli-plugins" && mv docker-scout "$HOME/.docker/cli-plugins/docker-scout"
        cat > "$HOME/.docker/cli-plugins.json" << 'EOF'
        {
          "cliPluginsExtraDirs": [
            "$HOME/.docker/cli-plugins"
          ]
        }
        EOF

    - name: Install snyk
      if: ${{ inputs.snyk-version != '' }}
      uses: snyk/actions/setup@v1
      with:
        snyk-version: ${{ inputs.snyk-version }}

    - name: Install bats
      if: ${{ inputs.bats-version != '' }}
      uses: bats-core/bats-action@3.0.1
      with:
        bats-version: ${{ inputs.bats-version }}
