# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: gha-tools-actions integration tests

on:
  workflow_call:

    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: 1password vault services account token
        required: false

permissions:
  contents: read

jobs:

  install-package-tests:
    name: validate all packages supported by the install action
    runs-on: ubuntu-latest

    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: install all packages supported by the install action
        uses: twplatformlabs/gha-tools-actions/install@main
        with:
          op-version: latest
          vault-version: latest
          teller-version: latest
          scout-version: latest
          snyk-version: latest
          bats-version: latest
          oras-version: latest
          cosign-version: latest

      - name: validate installed packages
        shell: bash
        run: |
          op --help | grep "1Password CLI"
          vault --help | grep "Usage:"
          teller --help | grep "Usage:"
          docker scout --help | grep "Command line tool for Docker Scout"
          snyk --help | grep "Snyk CLI"
          bats --version | grep "Bats"
          oras --help | grep "Usage:"
          cosign --help | grep "Usage:"


  integration-tests:
    name: gha-tools-actions integration tests
    runs-on: ubuntu-latest
    container: ghcr.io/twplatformlabs/gha-tools-runner:2026.03

    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: load job credentials
        uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          GH_TOKEN: op://platform/svc-github/access-token
          DOCKER_LOGIN: op://platform/svc-github/username
          DOCKER_PASSWORD: op://platform/svc-github/access-token

      - name: validate confirm registry action
        uses: twplatformlabs/gha-tools-actions/confirm-registry@main
        with:
          registry: ghcr.io

      # - name: validate buildx image building action
      #   uses: twplatformlabs/gha-tools-actions/buildx@main

      # - name: validate bats image testing action
      #   uses: twplatformlabs/gha-tools-actions/bats@main

      # - name: validate sign-manifest action
      #   uses: twplatformlabs/gha-tools-actions/sign-manifest@main
